version: '3'
services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - app
    ports:
      - "8080:80"
    networks:
      - back

  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    environment:
      XDEBUG_REMOTE_HOST: "192.167.222.1"
      PHP_IDE_CONFIG: "serverName=Docker"
    networks:
      - back

  cli:
    build:
      context: ./docker/cli
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ./var/composer:/root/.composer/cache
    tty: true
    networks:
      - back

  postgres:
    image: postgres:11.2-alpine
    volumes:
      - ./var/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    networks:
      - back

networks:
  back:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.167.222.0/16
