version: '3'
services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - app
    ports:
      - "8080:80"

  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    environment:
      XDEBUG_REMOTE_HOST: "192.167.213.1"
      PHP_IDE_CONFIG: "serverName=Docker"

  cli:
    build:
      context: ./docker/cli
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ./var/composer:/root/.composer/cache
    tty: true

  postgres:
    image: postgres:11.2-alpine
    volumes:
      - ./var/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    ports:
      - "5432:5432"
